export const attorneys = [
  {
    slug:      'michael-reese',
    name:      'Michael R. Reese',
    initials:  'MRR',
    role:      'Founding Partner',
    location:  'New York',
    email:     'mreese@reesellp.com',
    phone:     '(212) 643-0500',
    image:     null,
    bioFull: [
      'Mr. Reese litigates consumer and antitrust cases as class actions and on behalf of individual clients.',
      'Prior to entering private practice in 2000, Mr. Reese served as an assistant district attorney at the Manhattan District Attorney\'s Office where he served as a trial attorney prosecuting both violent and white-collar crime.',
    ],
    education:  [],
    admissions: [],
    focus: ['Consumer Protection', 'Antitrust', 'Class Actions'],
  },
  {
    slug:      'sue-nam',
    name:      'Sue J. Nam',
    initials:  'SJN',
    role:      'Partner',
    location:  'New York',
    email:     null,
    phone:     '(212) 643-0500',
    image:     null,
    bioFull: [
      'Ms. Nam is based in New York, and she focuses on intellectual property and consumer class actions.',
      'Prior to joining the firm, Ms. Nam was the General Counsel for NexCen Brands, Inc., a publicly traded company that owned a portfolio of consumer brands in food, fashion and homeware.',
    ],
    education:  [],
    admissions: [],
    focus: ['Intellectual Property', 'Consumer Class Actions'],
  },
  {
    slug:      'carlos-ramirez',
    name:      'Carlos F. Ramirez',
    initials:  'CFR',
    role:      'Partner',
    location:  'New York',
    email:     null,
    phone:     '(212) 643-0500',
    image:     null,
    bioFull: [
      'Mr. Ramirez is based in New York, and he focuses his practice on the litigation of consumer class actions.',
      'Prior to entering private practice in 2001, Mr. Ramirez served as an Assistant District Attorney at the Manhattan District Attorney\'s Office where he served as a trial attorney prosecuting both violent and white-collar crimes.',
    ],
    education:  [],
    admissions: [],
    focus: ['Consumer Class Actions', 'Consumer Protection'],
  },
  {
    slug:      'george-granade',
    name:      'George V. Granade II',
    initials:  'GVGI',
    role:      'Partner',
    location:  'Los Angeles',
    email:     null,
    phone:     '(212) 643-0500',
    image:     null,
    bioFull: [
      'Mr. Granade is a partner at Reese LLP based in Los Angeles, focusing on consumer class actions.',
    ],
    education:  [],
    admissions: [],
    focus: ['Consumer Class Actions', 'Food & Beverage Litigation', 'False Advertising'],
    matters: [
      {
        name:        'Martin v. Cargill, Inc.',
        citation:    'Consumer Class Action',
        description: 'Settled for $6.1 million on behalf of consumers challenging product labeling practices.',
      },
      {
        name:        'Barron v. Snyder\'s-Lance, Inc.',
        citation:    'Consumer Class Action',
        description: 'Class action involving products labeled as "natural," challenging the accuracy of that designation under applicable consumer protection laws.',
      },
    ],
  },
  {
    slug:      'charles-moore',
    name:      'Charles D. Moore',
    initials:  'CDM',
    role:      'Associate',
    location:  'Minneapolis',
    email:     null,
    phone:     '(212) 643-0500',
    image:     null,
    bioFull: [
      'Mr. Moore is based in Minneapolis, Minnesota where he focuses on both consumer as well as employment class actions.',
    ],
    education:  [],
    admissions: [],
    focus: ['Consumer Class Actions', 'Employment Law'],
  },
  {
    slug:      'kate-stoia',
    name:      'Kate J. Stoia',
    initials:  'KJS',
    role:      'Of Counsel',
    location:  'San Francisco',
    email:     null,
    phone:     '(212) 643-0500',
    image:     null,
    bioFull: [
      'Ms. Stoia is based in San Francisco.',
      'Prior to joining the firm, Ms. Stoia was an associate specializing in general and corporate litigation and labor and employment law at Brobeck Phleger &amp; Harrison LLP, Gibson Dunn &amp; Crutcher LLP, and Clarence &amp; Snell LLP.',
    ],
    education:  [],
    admissions: [],
    focus: ['Consumer Litigation', 'Labor & Employment', 'Corporate Litigation'],
  },
];
